### ISSUE TITLE
Online indicator doesn't show at the right times

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#226]
I get an "online" indicator when the other player is not online, 
also missing an online indicator when the game is in "Waiting for X to play"

**Comment by Pz1c** [comment]
we have some limitation with checking online((
we get player list once per 5 minutes, so player for example should become offline after 1 minute will be marked as online 4 minutes more

but it's can be fixed in case app will use last online time instead of "online checkbox"
I'll see what I can do

increase frequency is not our way because server owner will be sad)

**Comment by Prulon** [comment]
You only need to update the online status when refreshing the main game list.
But the values should be updated based on that - makes sense? and indeed you can use the "last online time" for that.

Also pay attention to the "waiting" status, where currently the "online" status is missing

**Comment by Pz1c** [comment]
should be fixed
